# Установка базового образа Python
FROM python:3.10-slim

RUN mkdir /tests-project/

WORKDIR /tests-project/

# Установка postgresql и его разработческих заголовков
RUN apt update && apt install -y gnupg2 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8 && apt update && apt install -y libpq-dev postgresql-server-dev-15

# Установка зависимостей для компиляции пакетов
RUN apt-get update && apt-get install -y build-essential

# Копирование кода приложения
COPY . .

# Установка зависимостей с помощью pipenv
RUN pip install -r requirements-test.txt

#CMD python -m pytest tests/test_api_menus.py
